spring.application.name=idiomas-api
spring.ai.vertex.ai.gemini.project-id=gen-lang-client-0621044152
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.api-key=${GEMINI_API_KEY:AIzaSyDPhqyzquczUJ2GCp4Z-LncM45CF2eb-7M}
spring.ai.vertex.ai.gemini.model=gemini-1.5-flash